import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  gradientContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 70,
  },
  container: {
    width: '80%',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  text: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 20,
    textAlign: 'left',
    width: '100%',
  },
  input: {
    width: '100%',
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 20,
    backgroundColor: 'rgba(253, 253, 253, 0.97)',
    marginBottom: 15,
    paddingLeft: 10,
    color: '#20272F',
  },
  button: {
    width: '100%',
    height: 45,
    borderRadius: 25,
    backgroundColor: '#7a4dff',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 20,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  socialButton: {
    width: '100%',
    height: 45,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 15,
  },
  facebookButton: {
    backgroundColor: '#fff',
    marginTop: 90,
  },
  googleButton: {
    backgroundColor: '#fff',
    marginTop: 10,
  },
  socialButtonText: {
    color: 'black',
    fontSize: 16,
    marginLeft: 10,
  },
  icon: {
    width: 20,
    height: 20,
  },
  createAccountText: {
    marginTop: 15,
    color: '#fff',
    fontSize: 14,
    marginRight: 46,
    width: 221,
  },
  forgotPasswordText: {
    marginTop: 2,
    color: '#fff',
    marginRight: 120,
  },
  createAccountLink: {
    color: '#7a4dff',
    textDecorationLine: 'underline',
  },
  linkText: {
    color: '#7a4dff',
    textDecorationLine: 'underline',
  },

  arrowButton: {
    width: '15%',
    position: 'absolute',
    height: 45,
    borderRadius: 25,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 20,
    marginRight: 10,
  },
  arrowImage: {
    width: 20,
    height: 20,
  },
  
  //Home
   returnButton: {
    width: '15%',
    position: 'absolute',
    height: 45,
    borderRadius: 25,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 20,
    marginRight: 10,          
    marginLeft: 10,          
  },

    inputhomescr: {
    width: '100%',          
    height: 40,  
    borderColor: '#ccc',          
    borderWidth: 1,          
    borderRadius: 20,   
    backgroundColor: 'rgba(253, 253, 253, 0.97)',          
    marginBottom: 15,          
    paddingLeft: 10,          
    color: '#20272F',
  },

   sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 15,
    alignSelf: 'flex-start',
  },
  categoryList: {
    marginBottom: 20,
  },
  categoryCard: {
    alignItems: 'center',
    marginRight: 15,
  },
  categoryImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#555',
    marginBottom: 5,
  },
  categoryName: {
    color: '#fff',
    fontSize: 14,
  },
  productList: {
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
  },
  card: {
    width: '45%',
    margin: 5,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  image: {
    width: 100,
    height: 150,
    marginBottom: 10,
    resizeMode: 'cover',
  },
  name: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
    textAlign: 'center',
  },
  price: {
    fontSize: 14,
    color: '#666',
  },
});
